# Generated by Django 5.2.4 on 2026-09-04 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IPAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(unique=True)),
                ('http_proxy', models.CharField(blank=True, help_text='Example: http://user:pass@host:port', max_length=255, null=True)),
                ('https_proxy', models.CharField(blank=True, help_text='Example: http://user:pass@host:port', max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('last_used', models.DateTimeField(auto_now_add=True)),
                ('usage_count', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'ip_addresses',
                'indexes': [models.Index(fields=['is_active', 'usage_count'], name='ip_addresse_is_acti_66b684_idx')],
            },
        ),
    ]
