# Generated by Django 5.2.17 on 2026-09-15 11:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_ipaddress'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserHyperLiquidKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('master_wallet_address', models.CharField(max_length=255)),
                ('api_wallet_address', models.CharField(max_length=255)),
                ('api_private_key', models.CharField(max_length=255)),
                ('api_valid_days', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_hyperliquid_keys',
            },
        ),
    ]
