# Generated by Django 5.2.4 on 2025-07-19 07:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=100, unique=True)),
                ('symbol', models.CharField(max_length=20)),
                ('direction', models.CharField(choices=[('LONG', 'Long'), ('SHORT', 'Short')], max_length=20)),
                ('order_quantity', models.DecimalField(decimal_places=10, default=0, max_digits=20)),
                ('entry_price', models.DecimalField(decimal_places=10, default=0, max_digits=20)),
                ('exit_price', models.DecimalField(decimal_places=10, default=0, max_digits=20)),
                ('fee', models.DecimalField(decimal_places=10, default=0, max_digits=20)),
                ('pnl', models.DecimalField(decimal_places=10, default=0, max_digits=20)),
                ('status', models.CharField(choices=[('LONG', 'Long'), ('SHORT', 'Short')], default='POSITION', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'orders',
            },
        ),
    ]
