# Generated by Django 5.2.4 on 2025-07-31 06:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='order',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='exchange',
            field=models.CharField(choices=[('BINANCE', 'Binance'), ('BINANCE_FUTURES', 'Binance Futures'), ('OTHER', 'Other')], default='BINANCE', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='fee_currency',
            field=models.CharField(default='USDT', max_length=10),
        ),
        migrations.AddField(
            model_name='order',
            name='fee_rate',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='is_spot',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='leverage',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='order',
            name='pnl_percentage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='total_cost',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Open'), ('POSITION', 'Position'), ('CLOSED', 'Closed'), ('CANCELLED', 'Cancelled'), ('FAILED', 'Failed')], default='POSITION', max_length=20),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['user', 'status'], name='orders_user_id_17dbdf_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['symbol', 'created_at'], name='orders_symbol_776fb4_idx'),
        ),
    ]
