# Generated by Django 5.2.4 on 2025-07-31 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0002_alter_order_options_order_closed_at_order_exchange_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='fee',
            new_name='entry_fee',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='fee_currency',
            new_name='entry_fee_currency',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='fee_rate',
            new_name='total_fee',
        ),
        migrations.AddField(
            model_name='order',
            name='exit_fee',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='order',
            name='exit_fee_currency',
            field=models.CharField(default='USDT', max_length=10),
        ),
    ]
