# Generated by Django 5.2.4 on 2025-07-31 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0003_rename_fee_order_entry_fee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='final_quantity',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=20),
        ),
    ]
