# Generated by Django 5.2.4 on 2025-08-01 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0005_rename_order_spotorder'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='spotorder',
            new_name='spot_orders_user_id_26a731_idx',
            old_name='orders_user_id_17dbdf_idx',
        ),
        migrations.RenameIndex(
            model_name='spotorder',
            new_name='spot_orders_symbol_285cca_idx',
            old_name='orders_symbol_776fb4_idx',
        ),
        migrations.AlterModelTable(
            name='spotorder',
            table='spot_orders',
        ),
    ]
