# Generated by Django 5.2.4 on 2025-08-01 08:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0006_rename_orders_user_id_17dbdf_idx_spot_orders_user_id_26a731_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FutureOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=100, unique=True)),
                ('symbol', models.CharField(max_length=20)),
                ('direction', models.CharField(choices=[('LONG', 'Long'), ('SHORT', 'Short')], max_length=20)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('POSITION', 'Position'), ('CLOSED', 'Closed'), ('CANCELLED', 'Cancelled'), ('FAILED', 'Failed')], default='POSITION', max_length=20)),
                ('leverage', models.IntegerField(default=1)),
                ('order_quantity', models.DecimalField(decimal_places=10, default=0, max_digits=20)),
                ('entry_price', models.DecimalField(decimal_places=10, default=0, max_digits=20)),
                ('entry_fee', models.DecimalField(decimal_places=10, default=0, max_digits=20)),
                ('entry_fee_currency', models.CharField(default='USDT', max_length=10)),
                ('stop_loss_order_id', models.CharField(max_length=100, unique=True)),
                ('stop_loss_price', models.DecimalField(decimal_places=10, default=0, max_digits=20)),
                ('stop_loss_fee', models.DecimalField(decimal_places=10, default=0, max_digits=20)),
                ('stop_loss_status', models.CharField(choices=[('OPEN', 'Open'), ('POSITION', 'Position'), ('CLOSED', 'Closed'), ('CANCELLED', 'Cancelled'), ('FAILED', 'Failed')], default='POSITION', max_length=20)),
                ('tp_order_id', models.CharField(max_length=100, unique=True)),
                ('tp_price', models.DecimalField(decimal_places=10, default=0, max_digits=20)),
                ('tp_fee', models.DecimalField(decimal_places=10, default=0, max_digits=20)),
                ('tp_status', models.CharField(choices=[('OPEN', 'Open'), ('POSITION', 'Position'), ('CLOSED', 'Closed'), ('CANCELLED', 'Cancelled'), ('FAILED', 'Failed')], default='POSITION', max_length=20)),
                ('total_fee', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('pnl', models.DecimalField(decimal_places=10, default=0, max_digits=20)),
                ('pnl_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'future_orders',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'status'], name='future_orde_user_id_4572f0_idx'), models.Index(fields=['symbol', 'created_at'], name='future_orde_symbol_9bccf0_idx')],
            },
        ),
    ]
