# Generated by Django 5.2.4 on 2025-09-08 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0007_futureorder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='futureorder',
            name='tp_order_id',
            field=models.CharField(max_length=100),
        ),
    ]
