# Generated by Django 5.2.4 on 2026-09-04 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0012_add_ignore_opposite_signal'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='futuretakeprofit',
            new_name='future_take_order_i_08d59d_idx',
            old_name='trade_fut_tp_status_idx',
        ),
    ]
