# Generated by Django 5.2.17 on 2026-09-06 04:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0013_rename_trade_fut_tp_status_idx_future_take_order_i_08d59d_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TradeSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('futures_max_positions', models.PositiveIntegerField(default=7)),
                ('futures_max_long', models.PositiveIntegerField(default=4)),
                ('futures_max_short', models.PositiveIntegerField(default=4)),
                ('spot_max_positions', models.PositiveIntegerField(default=7)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='trade_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'trade_settings',
            },
        ),
    ]
