# Generated by Django 5.2.17 on 2026-09-06 05:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0014_tradesettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradesettings',
            name='futures_leverage',
            field=models.PositiveIntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(125)]),
        ),
        migrations.AddField(
            model_name='tradesettings',
            name='futures_position_pct',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=5, validators=[django.core.validators.MinValueValidator(0.01), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='tradesettings',
            name='spot_position_pct',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=5, validators=[django.core.validators.MinValueValidator(0.01), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
