# Generated by Django 5.2.17 on 2026-09-07 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0016_spottakeprofit'),
    ]

    operations = [
        migrations.AddField(
            model_name='spotorder',
            name='dca_order_id',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='spotorder',
            name='dca_price',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='spotorder',
            name='dca_quantity',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='spotorder',
            name='dca_status',
            field=models.CharField(choices=[('OPEN', 'Open'), ('POSITION', 'Position'), ('CLOSED', 'Closed'), ('CANCELLED', 'Cancelled'), ('FAILED', 'Failed')], default='CANCELLED', max_length=20),
        ),
    ]
