# Generated by Django 5.2.17 on 2026-09-09 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0017_spotorder_dca_order_id_spotorder_dca_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='futureorder',
            name='move_sl_to_breakeven',
            field=models.BooleanField(default=False),
        ),
    ]
