# Generated by Django 5.2.17 on 2026-09-11 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0018_futureorder_move_sl_to_breakeven'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradesettings',
            name='sync_risk_from_webhook',
            field=models.BooleanField(default=True),
        ),
    ]
