# Generated by Django 5.2.17 on 2026-09-15 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0019_tradesettings_sync_risk_from_webhook'),
    ]

    operations = [
        migrations.AddField(
            model_name='futureorder',
            name='exchange',
            field=models.CharField(choices=[('BINANCE', 'Binance'), ('BINANCE_FUTURES', 'Binance Futures'), ('HYPERLIQUID', 'HyperLiquid'), ('OTHER', 'Other')], default='BINANCE_FUTURES', max_length=20),
        ),
        migrations.AlterField(
            model_name='spotorder',
            name='exchange',
            field=models.CharField(choices=[('BINANCE', 'Binance'), ('BINANCE_FUTURES', 'Binance Futures'), ('HYPERLIQUID', 'HyperLiquid'), ('OTHER', 'Other')], default='BINANCE', max_length=20),
        ),
    ]
