# Generated by Django 5.2.17 on 2026-09-17 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0020_futureorder_exchange_alter_spotorder_exchange'),
    ]

    operations = [
        migrations.AddField(
            model_name='futuretakeprofit',
            name='pnl',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='spottakeprofit',
            name='pnl',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=20),
        ),
    ]
