# Generated by Django 5.2.17 on 2026-09-18 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0021_futuretakeprofit_pnl_spottakeprofit_pnl'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_body', models.TextField(blank=True, default='')),
                ('payload', models.JSONField(blank=True, null=True)),
                ('action', models.CharField(blank=True, default='', max_length=50)),
                ('symbol', models.CharField(blank=True, default='', max_length=20)),
                ('side', models.CharField(blank=True, default='', max_length=10)),
                ('market', models.CharField(blank=True, default='', max_length=10)),
                ('exchange', models.CharField(blank=True, default='', max_length=20)),
                ('status', models.CharField(choices=[('RECEIVED', 'Received'), ('PROCESSED', 'Processed'), ('ERROR', 'Error')], default='RECEIVED', max_length=20)),
                ('error_message', models.TextField(blank=True, default='')),
                ('remote_addr', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'webhook_logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['created_at'], name='webhook_log_created_33987a_idx'), models.Index(fields=['symbol', 'created_at'], name='webhook_log_symbol_3099f5_idx'), models.Index(fields=['status', 'created_at'], name='webhook_log_status_9b19f7_idx')],
            },
        ),
    ]
