# Generated by Django 5.2.17 on 2026-09-24 06:39

import django.core.validators
from django.db import migrations, models
from django.utils import timezone


def grace_period_for_existing_users(apps, schema_editor):
    """Without this, every existing user with sync_risk_from_webhook=True
    would have last_market_risk_update=NULL right after this deploys, which
    `is_market_data_stale()` treats as stale -- i.e. new trades for
    everyone would halt bot-wide the instant this migration runs, rather
    than only after a real webhook outage. Stamp "now" for them instead, so
    the staleness clock starts fresh at deploy time and only trips on an
    actual future gap in the webhook feed. New users created after this
    migration still start at NULL (stale until their first real update),
    which is the intended behavior.
    """
    TradeSettings = apps.get_model("trade", "TradeSettings")
    TradeSettings.objects.filter(
        sync_risk_from_webhook=True, last_market_risk_update__isnull=True
    ).update(last_market_risk_update=timezone.now())


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0022_webhooklog'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradesettings',
            name='last_market_risk_update',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tradesettings',
            name='max_market_data_age_minutes',
            field=models.PositiveIntegerField(default=30, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1440)]),
        ),
        migrations.RunPython(
            grace_period_for_existing_users, migrations.RunPython.noop
        ),
    ]
